cd C:\kafka_2.13-2.7.0
.\bin\windows\zookeeper-server-start.bat .\config\zookeeper.properties

cd C:\kafka_2.13-2.7.0
.\bin\windows\kafka-server-start.bat .\config\server.properties

run :
	python all-compamy.py
	python user-credential.py
	python userDetails.py
	python recruterSignUp.py      
	python verifyemail.py  
	python EditProfile.py

	
	python slackSendMessage.py
	python bot2.py
	python consumer.py
	